# Generated by Django 4.1.5 on 2023-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlocation',
            name='cartesian_latitude',
            field=models.FloatField(blank=True, default=-1.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pointlocation',
            name='cartesian_longitude',
            field=models.FloatField(blank=True, default=-1.0, max_length=100),
        ),
    ]
