# Generated by Django 4.1.5 on 2023-09-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_pointlocation_cartesian_latitude_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpaceRoutes',
            new_name='SpaceRoute',
        ),
    ]
