# Generated by Django 4.1.5 on 2023-09-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_rename_spaceroutes_spaceroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceroute',
            name='Space Name',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
