# Generated by Django 4.1.5 on 2023-09-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_spaceroute_space name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spaceroute',
            old_name='Space Name',
            new_name='name',
        ),
    ]
