# Generated by Django 4.1.5 on 2023-09-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_rename_space name_spaceroute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlocation',
            name='type',
            field=models.CharField(choices=[('route', 'Route'), ('area', 'Area'), ('point', 'Point')], default='point', max_length=20),
        ),
    ]
