# Generated by Django 4.1.5 on 2023-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_pointlocation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceroute',
            name='space_area',
            field=models.ManyToManyField(to='routes.pointlocation'),
        ),
    ]
